### ISSUE TITLE
Doesn't Work on Earlier Instances

### ISSUE THREAD

**Issue by Andalusio** [DFranzen/cordova-FileStorage#1]
_UPDATE: Forgot to say that I wrote uri = "file:///...." + filename during gameplay, but "file:///....file.txt" in the option screen scenario. The gameplay takes place in an iFrame. Just so you know._

Hi. I'm updating my game at the moment, "Orenjin Pets", for Android, and I have to say that FileStorage is a live-saver. Before I discovered this plugin, my game wouldn't save anything via my previous, otherwise more popular (for some reason) plugin. I even had to use AJAX for loading.
 
But, my game's option screen via the main title is having trouble saving anything, especially my game's language in simple alphabets. It creates the text file just fine, but glitches with overwriting, that FileStorage cannot re-fire. Fire it via JQuery "Click" event by tapping on preferred flag that represents a language. (When I do load either of my pets, FileStorage works fine (mostly).)

**Comment by DFranzen** [comment]
Hey,

thanks for your interest in my Plugin. It’s not that old yet and I have written in mostly for my own Project. 
Ia am happy to have a look into it. Could you share your Code with me, so I can have a look at how you are using the plugin?
Otherwise just give me a bit more Information on how you are using the plugin, where you are trying to store the file, which APIs are being called in order to reproduce the glitch.
I assume you are using the newest Version of the plugin, could you let me know which Android Version you are testing under, because the plugin behaves slightly different depending on the Android Version.

Thanks
Daniel

Von: Andalusio
Gesendet: Freitag, 21. Juli 2017 22:36
An: DFranzen/cordova-FileStorage
Cc: Subscribed
Betreff: [DFranzen/cordova-FileStorage] Doesn't Work on Earlier Instances (#1)

Hi. I'm updating my game at the moment, "Orenjin Pets", for Android, and I have to say that FileStorage is a live-saver. Before I discovered this plugin, my game wouldn't save anything via my previous, otherwise more popular (for some reason) plugin. I even had to use AJAX for loading.
But, my game's option screen via the main title is having trouble saving anything, especially my game's language in simple alphabets. It creates the text file just fine, but glitches with overwriting, that FileStorage cannot re-fire. Fire it via JQuery "Click" event by tapping on preferred flag that represents a language. (When I do load either of my pets, FileStorage works fine (mostly). :)

**Comment by Andalusio** [comment]
As requested, here are my code samples: [http://www.manurrworkshop.com.ng/js.zip](http://www.manurrworkshop.com.ng/js.zip). Index.js is the code for the index homepage, and petroom.js is the gameplay/iFrame page. FileStorage worked well in the latter.
 
My current Android OS is Nougat (7.1.2). And yeah, it seems to be the latest version of your plugin I'm using.

**Comment by Andalusio** [comment]
Hey again. I think I figured out why FileStorage works during gameplay, and not on my Index file.
 
Apparently, during onClick events (or ".click" on JQuery), every other element references should be left off in the main/secondary functions that call the FileStorage function. I.e, when calling FileStorage, when clicking on images to hide/show others, like images of on and off buttons, the button references should be called separately from conditions calling FileStorage. E.g.:
 
$("#button1").hide();
$("#button2").show();
if(saveLoad == 0)
{
   saveLoad = 1;
   createFile(); //<-- This calls the FileStorage function.
}

... instead of...
 
if(saveLoad == 0)
{
   saveLoad = 1;

   $("#button1").hide();
   $("#button2").show();
   createFile(); //<-- This calls the FileStorage function.
}

The latter was my problem.

Ideally, **SetInterval**, at least in my project, should every 10 seconds re-fire FileStorage, in case the previous attempts didn't work. I think you should add such timer programmers may use till the Success or Error function is fired, or, at least, inform programmers to make theirs.
 
Have a great weekend! ;)

**Comment by Andalusio** [comment]
Hey again. Forgot to mention that your plugin now works. It must be from switching computers, but noticed a few codes I was supposed to add in my js files were missing or not implemented correctly.
 
Again, Lee up the good work.
